[package]
name = "nameless"
version = "0.0.0"
description = "Portable everything-is-a-URL"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["cli", "file", "network"]
categories = ["command-line-interface", "filesystem", "network-programming"]
repository = "https://github.com/sunfishcode/nameless"
readme = "README.md"

[dependencies]
anyhow = "1.0.34"
data-url = "0.1.0"
flate2 = "1.0.19"
memchr = "2.3.4"
mime = "0.3.16"
mime_guess = "2.0.3"
once_cell = "1.3.1"
parking = "2.0.0"
percent-encoding = "2.1.0"
readwrite = { version = "0.1.2", optional = true }
ureq = { version = "1.5.1", default-features = false, features = ["tls", "charset"] }
url = "2.1.1"

[target.'cfg(not(windows))'.dependencies]
shell-words = "1.0.0"

[dev-dependencies]
humantime = "2.0.1"
kommand = { path = "kommand" }
reaktor = { path = "reaktor" }
paw = "1.0.0"
regex = "1.4.2"
structopt = { version = "0.3.20", features = ["paw"] }

[features]
default = []
nightly = []

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = [
  "kommand",
  "reaktor",
]
