[package]
name = "nameless"
version = "0.0.0"
description = "Portable everything-is-a-URL"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["file", "network"]
categories = ["filesystem", "network-programming"]
repository = "https://github.com/sunfishcode/nameless"
readme = "README.md"

[dependencies]
anyhow = "1.0.33"
data-url = "0.1.0"
flate2 = "1.0.18"
mime = "0.3.16"
mime_guess = "2.0.3"
ureq = { version = "1.5.1", default-features = false, features = ["tls", "charset"] }
url = "2.1.1"
percent-encoding = "2.1.0"

[dev-dependencies]
structopt = { version = "0.3.20", features = ["paw"] }
paw = "1.0.0"
regex = "1.4.2"
kommand = { path = "kommand" }

[features]
default = []
nightly = []

[badges]
maintenance = { status = "actively-developed" }
